 var max_wall_width = 5;
 
 var laser_length = 1;
 var laser_radius = 7/32;
 
 var sprayer_width = 9/16;
 var sprayer_length = 2 + 5/16;
 var sprayer_height = 1 + 5/8;
 
 var motor_radius = 0.5;
 
 var breadboard_length = 1 + 7/8 + 1/16;
 var breadboard_height = 1 + 3/8;
 var breadboard_thickness = 5/8;
 
 var bottle_height = 8.75;
 var bottle_radius = 2.75; bottle_radius /= 2;
 var bottle_neck_radius = 1 + 3/8; bottle_neck_radius /= 2;
 
 var thickness = 3/16;
 
 var wire_width = 3/32;
 
 function Base()
 {
     var base = cube([thickness,breadboard_length + thickness*4 + laser_radius*2 + bottle_radius*2,1 + max(breadboard_height, motor_radius*2) + thickness*2]);
     base = base.translate([0,0,bottle_height - sprayer_height + thickness]);
     
     //track and handle
     var track = cylinder({'r': 7/16, 'h': thickness*2 + wire_width*3}).rotateY(90).translate([0,7/16,7/32]);
     track = difference(track, cylinder({'r': 7/16, 'h': 1}).translate([thickness*3 + wire_width, 7/16, -0.25]));
     track = difference(track, cube([7/8, 7/8, 1]).translate([thickness*2 + wire_width*3 - 7/16, 7/16, -0.25]));
     track = union(track, cube([thickness*2 + wire_width*3,breadboard_length/2 + thickness/2 + laser_radius + bottle_radius,thickness*2 + wire_width]));
     track = union(track, cylinder({'r': 3/16, 'h': wire_width + thickness*2}).translate([thickness*3 + wire_width, 7/16, 0]));
     base = union(base, track.translate([thickness,breadboard_length/2 + thickness*2 + laser_radius + bottle_radius, bottle_height + 0.5 + 1/8]));
     
     var cutout = cube([thickness*2 + wire_width*3,breadboard_length + thickness + laser_radius*2 + bottle_radius*2, wire_width]);
     base = difference(base, cutout.translate([0,thickness,bottle_height + 0.5 + thickness + 1/8]));
     base = difference(base, cutout.scale([(wire_width*3)/(wire_width*3 + thickness*2),1,1]).rotateY(90).translate([thickness*2 + wire_width,thickness,bottle_height + 0.5 + thickness + wire_width*2 + 1/8]));
     
     //breadboard inlay???
     var inlay = cube([bottle_radius - sprayer_width/2 + thickness, breadboard_length + thickness*2, breadboard_height + thickness*2]);
     inlay = inlay.translate([-bottle_radius + sprayer_width/2, bottle_radius*2 + thickness, bottle_height - sprayer_height + thickness]);
     
     base = difference(base, inlay);
     
     inlay = difference(inlay, cube([bottle_radius-sprayer_width + thickness*2, breadboard_length, breadboard_height]).translate([-bottle_radius + sprayer_width/2 + thickness, bottle_radius*2 + thickness*2, bottle_height - sprayer_height + thickness*2]));
      
     base = union(base, inlay);
     
     //laser and sensor
        //laser
        var laser = cube([laser_length + 1/4, laser_radius*2, laser_radius + 1/8]).translate([0,0,-1/8]);
        laser = difference(laser, cylinder({'r' : laser_radius, 'h' : laser_length}).rotateY(90).translate([0,laser_radius,laser_radius]));
        laser = difference(laser, cylinder({'r' : laser_radius*.75, 'h' : laser_length}).rotateY(90).translate([1,laser_radius,laser_radius]));
        laser = difference(laser, cube([1/16, laser_radius*2, laser_radius*2]).translate([laser_length + 3/32,0,0]));
        laser = difference(laser, cube([laser_length, laser_radius*2, laser_radius*2]).translate([0,0,laser_radius - 3/32]));
        
        base = union(base, laser.translate([thickness,bottle_radius*2 + breadboard_length + thickness*2.5, bottle_height - sprayer_height/4 + laser_radius + 1/8]));
        
        //sensor - pointing down
        var sensor = cube([wire_width*2, wire_width*5, 0.5]);
        
        sensor = difference(sensor, cube([wire_width*2, wire_width, 0.5]).translate([0,wire_width*2,0]));
        sensor = difference(sensor, cube([wire_width, wire_width*3, 0.5 - wire_width]).translate([0,wire_width,0]));

        
        base = union(base, sensor.translate([thickness,bottle_radius*2 + breadboard_length + thickness*1.5 + wire_width*1.8, bottle_height - 0.85]));
     
     //cover snaps
     
     
     return base;
 }
 
 function Cover()
 {
     return cube();
 }
 
 function Sprayer()
 {
     var sprayer = cube([sprayer_length,sprayer_width,sprayer_width]);
     
     
     sprayer = sprayer.translate([-sprayer_width/2,-sprayer_width/2,bottle_height - sprayer_width]);     

     var bottle = cylinder({'r': bottle_radius, 'h' : bottle_height - sprayer_height});
     
     return union(sprayer,bottle);
 }
 
 function main()
 {
     var base = Base();
     
     var cover = Cover();
     
     var sprayer = Sprayer();
     sprayer = sprayer.translate([sprayer_width/2 + thickness,bottle_radius,0]);
     
     return union(  base.setColor([0.2,0.2,0.2]),
                    //cover.setColor([0,0,0]),
                    sprayer.setColor([0.5,0.5,0.5]));
 }
