 var max_wall_width = 5;
 
 var laser_length = 1;
 var laser_radius = 7/32;
 
 var breadboard_length = 1 + 7/8 + 1/16;
 var breadboard_height = 1 + 3/8;
 var breadboard_thickness = 5/8;
 
 var bottle_height = 8.75;
 var bottle_radius = 2.75; bottle_radius /= 2;
 var bottle_neck_radius = 1 + 3/8; bottle_neck_radius /= 2;
 
 function main()
 {
     
     return cube();
 }
