 var max_wall_width = 5;
 
 var laser_length = 1;
 var laser_radius = 7/32;
 var laser_big_radius = 7/16;
 var laser_offset = 5/8;
 
 var sprayer_width = 9/16;
 var sprayer_length = 2 + 5/16;
 var sprayer_height = 1 + 5/8;
 
 var motor_radius = 15/16; motor_radius /= 2;
 var motor_length = 1 + 1/8;
 var gear_offset = 1/16;
 var gear_width = 3/16;
 var gear_radius = 1/4;
 
 var spring_delta = 1/4;
 
 var breadboard_length = 1 + 7/8 + 1/16;
 var breadboard_height = 1 + 3/8;
 var breadboard_thickness = 5/8;
 
 var bottle_height = 8.75;
 var bottle_radius = 2.75; bottle_radius /= 2;
 var bottle_neck_radius = 1 + 3/8; bottle_neck_radius /= 2;
 var bottle_neck_offset = 5/8;
 
 var thickness = 3/16;
 
 var wire_width = 3/32;
 
 var base_size = [thickness, breadboard_length + thickness*4 + laser_radius*2 + bottle_radius*2, 1 + breadboard_height + thickness*2];
 
 //track
 var pin_width = wire_width;
 var handle_radius = 7/16;
 var full_track_length = base_size[1] - thickness*3;
 var handle_length = full_track_length/2 + thickness*2;
 var track_size  = [thickness*2 + wire_width*3, full_track_length/2 + thickness/2, thickness*2 + wire_width];
 
 function Base()
 {
     var base = cube(base_size);
     
     //track and handle
     var track = cylinder({'r': handle_radius, 'h': thickness*2 + wire_width*3}).rotateY(90).translate([0,handle_radius,handle_radius/2]);
     track = difference(track, cylinder({'r': handle_radius, 'h': 1}).translate([thickness*3 + wire_width, handle_radius, -0.25]));
     track = difference(track, cube([handle_radius*2, handle_radius*2, 1]).translate([thickness*2 + wire_width*3 - handle_radius, handle_radius, -0.25]));
     track = union(track, cube(track_size));
     track = union(track, cylinder({'r': 3/16, 'h': wire_width + thickness*2}).translate([thickness*3 + wire_width + 0.05, handle_radius, 0]));
     track = difference(track, cylinder({'r': pin_width*1.1/2, 'h': wire_width + thickness*2}).translate([thickness*3 + wire_width + 0.05, handle_radius, 0]));
     base = union(base, track.translate([thickness, handle_length - thickness, base_size[2] - track_size[2]/2 - 0.5]));
     
     var cutout = cube([thickness*2 + wire_width*3, full_track_length, wire_width]);
     base = difference(base, cutout.translate([0,thickness,base_size[2] - 0.5 - wire_width/2]));
     base = difference(base, cutout.scale([(wire_width*3)/(wire_width*3 + thickness*2),1,1]).rotateY(90).translate([thickness*2 + wire_width,thickness, base_size[2] - 0.5 + wire_width*1.5]));
     
     //breadboard inlay???
     var inlay = cube([bottle_radius - sprayer_width/2 + thickness, breadboard_length + thickness*2, breadboard_height + thickness*2]);
     inlay = inlay.translate([-bottle_radius + sprayer_width/2, bottle_radius*2 + thickness, 0]);
     
     base = difference(base, inlay);
     
     inlay = difference(inlay, cube([bottle_radius-sprayer_width + thickness*2, breadboard_length, breadboard_height]).translate([-bottle_radius + sprayer_width/2 + thickness, bottle_radius*2 + thickness*2, bottle_height - sprayer_height + thickness*2]));
      
     base = union(base, inlay);
     
     //laser and sensor
        //laser
        var laser = cube([laser_length + 1/4, laser_radius*2, laser_radius + 1/8]).translate([0,0,-1/8]);
        laser = difference(laser, cylinder({'r' : laser_radius, 'h' : laser_length}).rotateY(90).translate([0,laser_radius,laser_radius]));
        laser = difference(laser, cylinder({'r' : laser_radius*0.75, 'h' : laser_length}).rotateY(90).translate([1,laser_radius,laser_radius]));
        laser = difference(laser, cube([1/16, laser_radius*2, laser_radius*2]).translate([laser_length + 3/32,0,0]));
        laser = difference(laser, cube([laser_length, laser_radius*2, laser_radius*2]).translate([0,0,laser_radius - 3/32]));
        
        base = union(base, laser.translate([thickness,bottle_radius*2 + breadboard_length + thickness*2.5, bottle_height - sprayer_height/4 + laser_radius + 1/8]));
        
        //sensor - pointing down
        var sensor = cube([wire_width*2, wire_width*5, 0.5]);
        
        sensor = difference(sensor, cube([wire_width*2, wire_width, 0.5]).translate([0,wire_width*2,0]));
        sensor = difference(sensor, cube([wire_width, wire_width*3, 0.5 - wire_width]).translate([0,wire_width,0]));

        
        base = union(base, sensor.translate([thickness,bottle_radius*2 + breadboard_length + thickness*1.5 + wire_width*1.8, bottle_height - 0.85]));
     
     //cover snaps
     
     
     //holders
     
     return base;
 }
 
 function Slider()
 {
     
 }
 
 function Handle()
 {
     var handle = cylinder({'r': handle_radius, 'h': handle_length - handle_radius*2});
 
    handle = handle.rotateX(-90);
    
    var end = cylinder({'r': handle_radius, 'h': handle_radius*2}).translate([0,0,-handle_radius]);
    
    handle = union(handle, end);
    handle = union(handle, end.translate([0,handle_length - handle_radius*2,0]));
 
    handle = intersection(handle, handle.scale([1,3,1]).translate([0,-handle_length*0.75,0]));
 
    handle = difference(handle, cylinder({'r': pin_width*1.1/2, 'h': handle_radius*2}).translate([0, 0, -handle_radius]));
 
    handle = difference(handle, cube([track_size[0] + 1/8, track_size[1], track_size[2] + 1/8]).translate([-track_size[0] - 1/16, -0.4, -track_size[2]/2 - 1/16]));
 
    handle = difference(handle, cube([1,-1,track_size[2] + 1/8]).translate([-0.5, -0.05,-track_size[2]/2 - 1/16]));
    
    handle = difference(handle, cylinder({'r': 1/4, 'h': track_size[2] + 1/8}).translate([0,0,-track_size[2]/2 - 1/16]));
 
    return handle;
 }
 
 function Cover()
 {
     return cube();
 }
 
 function Sprayer()
 {
     var sprayer = cube([sprayer_length,sprayer_width,sprayer_width]);
     
     
     sprayer = sprayer.translate([-sprayer_width/2,-sprayer_width/2,bottle_height - sprayer_width]);     

     var bottle = cylinder({'r': bottle_radius, 'h' : bottle_height - sprayer_height});
     
     return union(sprayer,bottle);
 }
 
 function main()
 {
     var base = Base();
     base = base.translate([0,0,bottle_height - sprayer_height + thickness]);
     
     var cover = Cover();
     
     var sprayer = Sprayer();
     sprayer = sprayer.translate([sprayer_width/2 + thickness,bottle_radius,0]);
     
     var handle = Handle();
     handle = handle.translate([thickness*3 + wire_width*3 + 0.05,handle_length - thickness + handle_radius,bottle_height + 0.6 + handle_radius/2]);
     
     return union(  base.setColor([0.2,0.2,0.2]),
                    handle.setColor([0.2, 0.2, 0.2])
                    //cover.setColor([0,0,0]),
                    //sprayer.setColor([0.5,0.5,0.5])
                    );
 }
